# Generated by Django 5.0.2 on 2025-04-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('oil-change', 'Oil Change'), ('brake-service', 'Brake Service'), ('engine-repair', 'Engine Repair'), ('transmission', 'Transmission Service'), ('diagnostics', 'Diagnostics'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
